fallbacks: true
js_extend: false
sort_translation_keys: false

export_i18n_js: 'app/assets/javascripts/modules'

translations:
- file: 'app/assets/javascripts/translations/home-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.views.home.*', '*.js.views.header.*', '*.js.views.sidebar.*', '*.js.views.footer.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.comment.*', '*.js.bookmark.*', '*.js.checkbox.*', '*.js.languages.*']

- file: 'app/assets/javascripts/translations/user-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.views.home.*', '*.js.views.header.*', '*.js.views.sidebar.*', '*.js.views.footer.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.editor.*', '*.js.comment.*', '*.js.bookmark.*', '*.js.checkbox.*', '*.js.languages.*', '*.js.selecter.*']

- file: 'spec/javascripts/translations/%{locale}.js'
